### ISSUE TITLE
Option to save the converted images

### ISSUE THREAD

**Issue by alexander-akait** [zckrs/gulp-css-base64#25]
Remove converted images to base64 from assets folder

**Comment by evilebottnawi** [comment]
@zckrs plugins nit should remove image, he create array of images, fonts (etc) which were base64 encode
```javascript
.pipe(options.environment >= 2 ? $.cssBase64({
    baseDir: directory.srcBase64,
    base64DecoreFiles: []
}) : utils.noop())
```
After working base64DecoreFiles array must contain files which were base64 decode
