### ISSUE TITLE
Does this work with Sass .scss files?

### ISSUE THREAD

**Issue by felixfbecker** [zckrs/gulp-css-base64#29]
Sass doesn't fix relative urls so I tried running my .scss file through this before sass-compiling, but it doesn't work (the url stays the same). Sass is very similar to CSS so I expected it to work.

**Comment by zckrs** [comment]
No support for sass.  Use plugin after sass process on CSS file.

**Comment by felixfbecker** [comment]
I actually switched to Less because it has the relative url option
