### ISSUE TITLE
Remove dependency on deprecated gulp-util?

### ISSUE THREAD

**Issue by ajssd** [zckrs/gulp-css-base64#44]
Any chance of replacing the dependency on deprecated gulp-util (and maybe bumping the versions of the other dependencies at the same time)?

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by stelgenhof** [comment]
Second that. The package also uses a version of lodash-template that has a security vulnerability: https://github.com/lodash/lodash/pull/4336

**Comment by zckrs** [comment]
Done and release into https://github.com/zckrs/gulp-css-base64/releases/tag/v2.0.0
